version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: eduquiz-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eduquiz
      MYSQL_USER: eduquiz
      MYSQL_PASSWORD: eduquiz123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 